# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
   
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: gd
    cache: default
    webp:
        generate: true
    filter_sets:
        card: #nom du filtre
            quality: 60 #Qualite de l'image
            filters:
                thumbnail: {size: [120, 120], mode: outbound}
        echelle:
            quality: 85 #Qualite de l'image
            filters:
                scale:
                    dim: [250, 250]
        product:
            quality: 75 #Qualite de l'image
            filters:
                upscale:
                    min: [800, 400]
                thumbnail: { size: [800, 400], mode: outbound }
        thumbnail:
            quality: 60
            filters:
                thumbnail:
                    size: [120, 120]
                    mode: outbound
          
                    
                


